server {
    listen: 80;
    # server-name travelmates-app.fr www.travelmates-app.fr;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri/ /index.html;
    }
}