build-prod:
  image: docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd travel-mates
    - |
      docker build \
        --build-arg VITE_API_BASE_URL="$VITE_API_BASE_URL" \
        --build-arg VITE_UNSPLASH_API_KEY="$VITE_UNSPLASH_API_KEY" \
        --build-arg VITE_MAPBOX_API_KEY="$VITE_MAPBOX_API_KEY" \
        --build-arg VITE_MAPBOX_SESSION_TOKEN="$VITE_MAPBOX_SESSION_TOKEN" \
        -t "$CI_REGISTRY_IMAGE:$TAG_PROD" \
        -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$TAG_PROD"
  rules:
    - when: manual